---
sidebar: sidebar 
permalink: use/capacity-add.html 
keywords: economic efficiency remediate, economic efficiency, capacity planning, add capacity 
summary: Economic Efficiencyサービスは、予測されるデータ増加量に基づいて、AFF システムに関する推奨事項を提供します。予測を受け入れるか、独自の予測を入力できます。これに基づいて、容量の増加予測を満たす、資産構成に最適な推奨事項が提示されます。 
---
= 容量を追加します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Economic Efficiencyサービスは、予測されるデータ増加量に基づいて、AFF システムに関する推奨事項を提供します。予測を受け入れるか、独自の予測を入力できます。これに基づいて、容量の増加予測を満たす、資産構成に最適な推奨事項が提示されます。

たとえば、既存のシリアル番号にシェルフを追加して容量を追加することを推奨します。

提案書は、見積もりのリクエストとして、または代替オプションのリクエストとして、ネットアップの営業チームに簡単に提出できます。

.手順
. BlueXPの左側のナビゲーションで、* Governance *>* Economic Efficiency *>* Capacity Planning *を選択します。
. アセットの*[Evaluate Storage Options]*を選択します。
. [容量の追加]*を選択します。
+
アセットのデータが表示されます。

+
** 予測、利用率、レイテンシのトレンド、IOPSのトレンドを確認します。
** 推奨事項を確認するには、*[ストレージオプションの評価]*を選択します。
+
[Define Capacity Requirements]ページには、現在の容量予測と予測される容量予測、および予測される増加に基づいて推奨される増設用ストレージが表示されます。



. 右側のオプションのいずれかを選択します。
+
** *予測される増加率*に基づいて追加ストレージを推奨し、必要に応じてバッファパーセンテージを追加します。
** *カスタムデータの増加に基づいてアドオンストレージを推奨*し、推奨される容量ではなく、必要な合計アドオン容量を入力します。


. 「 * Continue * 」を選択します。
+
一連の推奨事項が表示されます。

. 選択したアセットのシリアル番号に関する推奨事項を確認します。
. 次のいずれかを実行します。
+
** 推奨事項を受け入れるには、*[次へ]*を選択します。リクエストはネットアップの営業エキスパートに送信され、ネットアップの営業エキスパートがお客様と連携して、必要な追加容量を確保します。
** 別のオプションをリクエストするには、*[代替オプションのリクエスト]*を選択し、リクエストを入力して*[電子メールの送信]*を選択します。ネットアップの営業エキスパートが容量要件に対応するためにご連絡するEメールが送信されます。


. 追加容量の申請を確認し、*[確認して送信]*を選択します。
+
[Capacity Planning Status]ページが表示されます。

. [Capacity Planning Status]ページでステータスを確認します。

