---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp economic efficiency works, what is economic efficiency, bluexp 
summary: キャパシティプランニングサービスは、現在または予測される低容量のクラスタを特定し、データ階層化または追加容量（AFF システムの場合）に関する推奨事項を提供します。 
---
= 経済効率化サービスについて説明します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
システムの容量不足による不要なダウンタイムを回避するには、キャパシティプランニングが不可欠です。NetApp BlueXP Economic Efficiencyサービスでは、次のことを実現できます。

* 容量が少ないクラスタを特定します。
* クラスタをレビューして現在の容量と予測される容量を確認します。
* CPU利用率、IOPSパフォーマンス、レイテンシパフォーマンスをレビューして、容量修正の余地を特定します。


Economic Efficiencyサービスは、現在または予測される低容量のクラスタを特定し、データ階層化または容量の追加に関する推奨事項（AFF システムの場合）を提供します。容量を追加することを選択した場合は、詳細な推奨事項を記載したリクエストがパートナー様とネットアップの担当者に転送されます。このリクエストには、容量の選択と発注リクエストを簡単に行うために必要な詳細情報が含まれています。

このサービスには、BlueXPの* Governance *カテゴリからアクセスできます。

経済効率化サービス環境 オンプレミスAFF システムのみ（Unified AFF システムとオールSANアレイシステムを含む）



== 経済効率化サービスの利点

Economic Efficiencyサービスには、次のようなメリットがあります。

* 容量を追加するための簡単なプロセスを提供します
* お客様の環境の容量の問題に対処するための、信頼できるアドバイザーと推奨事項を提供
* ストレージの追加計画にかかる時間を短縮します




== コスト

ネットアップは、このサービスの利用に対して料金を請求することはありません。コールドデータをクラウドストレージに階層化する場合は、クラウドプロバイダで該当する料金を確認する必要があります。
