---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, economic efficiency frequently asked questions 
summary: BlueXPの経済効率化サービスは、容量が現在または予測される低いクラスタを特定し、データの階層化や容量の追加（AFF システムの場合）に関する推奨事項を提供します。サポート終了が近づいているシステムに関する機器更改に関する推奨事項も提供されます。 
---
= 新機能
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXPの経済性に関する最新情報をご紹介します。



== 2024年5月15日



=== 無効な機能

BlueXP  の経済効率化機能の一部が一時的に無効になりました。

* テクノロジの更新
* 容量を追加します




== 2024年3月14日



=== テクノロジ更新オプション

既存の資産を運用していて、テクノロジの更新が必要かどうかを判断する場合は、BlueXPの経済性に関するテクノロジ更新オプションを利用できます。現在のワークロードの簡単な評価を確認して推奨事項を確認できます。また、過去90日以内にAutoSupportログをNetAppに送信した場合は、新しいハードウェアでのワークロードのパフォーマンスを確認するためのワークロードシミュレーションを提供できるようになりました。

ワークロードを追加して、既存のワークロードをシミュレーションから除外することもできます。

これまでは、アセットの評価を受けて、テクノロジの更新が推奨されるかどうかを判断することしかできませんでした。

この機能は、左側のナビゲーションの機器更改（Tech Refresh）オプションに含まれるようになりました。

の詳細については、を https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["テクノロジの更新を評価する"]参照してください。



== 2023年11月8日



=== テクノロジの更新

今回リリースされたBlueXPの経済効率化機能には、資産を評価し、テクノロジの更新が推奨されるかどうかを確認する新しいオプションが含まれています。このサービスには、左側のナビゲーションにある新しい機器更改（Tech Refresh）オプションのほか、現在のワークロードと資産を評価するための新しいページ、推奨事項を記載したレポートが含まれています。



== 2023年4月2日



=== BlueXP  の経済効率化の導入

新しいBlueXPの経済効率化サービスは、現在または予測されている容量が少ないストレージ資産を特定し、オンプレミスのAFF システムのデータ階層化や容量の追加に関する推奨事項を提供します。

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["BlueXPの経済性に関する詳細はこちらをご覧ください"]。
